### ISSUE TITLE
Formatar código

### ISSUE THREAD

**Issue by tulioac** [eduardopds/vacinabrasil#2]
Recomendo utilizar identações para facilitar a leitura e desenvolvimento do seu código. Caso utilize o _VS Code_ como seu editor, pode-se instalar a extensão [**Prettier**](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) para formatar sem maiores dificuldades. :)

**Comment by eduardopds** [comment]
vlw :)
